# Generated by Django 5.1.2 on 2025-02-20 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InternshipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('year_of_study', models.CharField(max_length=50)),
                ('ssig_number', models.CharField(max_length=255)),
                ('special_lab', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('industry_address_1', models.CharField(max_length=255)),
                ('industry_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('original_certificate', models.FileField(upload_to='certificates/')),
                ('attested_certificate', models.FileField(upload_to='certificates/')),
                ('iqac_verification', models.CharField(default='Initiated', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=255)),
                ('internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.internship')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='To Do', max_length=50)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.internship')),
            ],
        ),
    ]
